### PR TITLE
Major refactoring, documenting and geoJSON viewing support

### LINKED ISSUE #50: Request - More complex location formats
It would be great to be able to specify polygons rather than individual points in some cases to specify an area rather than just a point.

### PR DESCRIPTION
**Pull request by gentlegiantJGC**
This is still work in progress but is mostly complete. I thought I would just open this so that you can see what I have been working on and give feedback.

This started out with the intention of adding geoJSON viewing support to the map plugin but has spiralled into more than that.

Adds support for the full geoJSON format within the front matter under the `geoJSON` key as well as within a code block of type geoJSON

Fixes #50 

- Added a large number of comments and docstrings.
- Renamed quite a few functions to better describe what they do.
- Reworked the behaviour of some functions.
- Moved all images into an img directory to declutter the root directory.
- Added the BaseGeoLayer class which FileMarker and GeoJSONLayer extend.
- Changed all typing to use the BaseGeoLayer class from which implementations extend.
- Added GeoJSONLayer class to handle the geoJSON type.
- Moved marker UI creation into the FileMarker class.
- Modified the build system so that `npm run dev` builds into the root directory so that the repository can be directly in the obsidian plugins directory.
- Rewritten regexes to use named capture groups rather than relying or ordering.
- Renamed urlConvertor to coordinateParser because the class is not limited to urls.
- Renamed a number of variables (and functions) containing `location` to `coordinate` to disambiguate from file location.
- Moved map setState and getState methods out of the constructor and into the class.
- Increased the max map zoom level so that you can zoom the map in further.
- Capped the maxNativeZoom (map tile zoom) to stop OSM tiles going blank when zooming in too far.
  - perhaps the maxNativeZoom should be configurable per map source.
- Modified leaflet Polygon behaviour to make it cluster.
- Improved the front matter handling.
  - The old implementation had bugs if the key exists but in a nested object.
  - The new implementation finds and parses the data as yaml and calls a callback to edit the loaded data before writing back.
    - This gives more control than the simple setdefault function that existed before.

(and probably other things I have forgotten about)

### CODE REVIEW

**Comment by esm7** [comment]
First and foremost, thanks for doing this, it will be a great contribution to Map View!
It will take me a few days to do a proper review and hopefully we can get it merged and released within an iteration or two :sunglasses: 
From a very fast skim through the changes it seems like high-quality refactoring and additions; one thing I don't like though (which is a matter of taste I guess) are the full 3-line docstrings in so many places.
I completely agree that this code requires much more documentation and greatly thank you for doing so, but -
1. I prefer to omit documentation that explains in one line what one line of code does, e.g. IMHO a method like `loadSettings` doesn't need 3 lines of a docstring to say "load the settings from disk".
2. Even when really useful, I prefer not to prepend each member in a type by 3 lines of a docstring; at least to me it takes too much screen real-estate when trying to work on the actual code. For members that are not self-explanatory I'd appreciate if you convert the documentation to ` // ` comments.
3. Is there a reason you use tags like `@private` in the docstrings? Isn't that why we use the Typescript `private` keyword?

A more comprehensive review will hopefully follow in the upcoming days :)

**Comment by gentlegiantJGC** [comment]
The docstrings were populated mostly by PyCharm and I just filled them in.
I am a Python developer and I have done very little JavaScript before so there may be other things I am applying python logic to that is wrong for JavaScript.
In python you write the docstring and there are tools that can build documentation from the source code. I don't know if JavaScript can do that from single line comments.
I was mostly adding docstrings so that I could hover on the function call and pycharm would display the documented function.

**Comment by gentlegiantJGC** [comment]
I would like to get this sorted. I have some more features that I would like to implement that will build upon these changes.
I will have a go at merging your previous changes.
My thoughts for more additions are:
1) Map overlay - overlay other map images on the leaflet map
2) Image pins with FOV indicator and thumbnail on hover (#16 might do some of this)
3) Embed the map into a file with the ability to specify attributes. The normal map is great but having presets in files would be great (eg a file containing a map with just images). This would also be good to visualise individual pins.
4) Adding the ability to filter pins by date (eg only show images between two dates)

**Comment by gentlegiantJGC** [comment]
It might be easiest if I split this into multiple pull requests since I am going to have to rewrite a lot of it anyway

**Comment by esm7** [comment]
I'm really sorry for the holdup; not sure how it slipped my mind, and that's surely not how your great contributions deserve to get treated :(
I'll do all it takes to review & merge next week :crossed_fingers:

**Comment by gentlegiantJGC** [comment]
Thanks. I am looking into splitting this into multiple pull requests to make it easier to merge.
I also need to work out how your changes effect it.

**Comment by gentlegiantJGC** [comment]
I am part way into splitting this pull request into multiple pull requests. This should make it easier to review since each pull request will concentrate on a single component. Some components do depend on other things so I will need to wait until you have merged the previous ones to continue.

As of currently:
#62 moves images into a sub-directory to declutter the root directory
#64 makes the development build easier to use by building into the root directory
#65 adds the comments and docstings that were added here
#63 implements prettier commands to standardise code style. Pull requests will make sure it has been run. I suggest merging this one last.

**Pull request closed without merging**
