### PR TITLE
Use Google Maps Place data in templates

### PR DESCRIPTION
**Pull request by HalFrgrd**
I really like this plugin and I've been using Templater to query the Google Maps Place API and automatically fill in details like:
- the type of place (`restaurant`, `cafe`, etc ...)
- the rating
- the `place_id` so I can build a direction URL and a search URL (https://developers.google.com/maps/documentation/urls/get-started)
- the more human friendly `name` attribute.
- address

Same issue as https://github.com/esm7/obsidian-map-view/issues/173

### Solution
A template can contain paths to data returned in the full [Google Maps places data](https://developers.google.com/maps/documentation/places/web-service/place-data-fields)
It would be easy to extend the solution to OSM.

#### Example
With this template:
```
---
gmaps_place_id: "{{googleMapsPlaceData.place_id}}"
address: "{{googleMapsPlaceData.formatted_address}}"
rating: "{{googleMapsPlaceData.rating}}"
---
#{{googleMapsPlaceData.types.0}}
main type of place: {{googleMapsPlaceData.types.0}}
all types: {{googleMapsPlaceData.types}}
opening_hours: {{googleMapsPlaceData.opening_hours.open_now}}
address: {{googleMapsPlaceData.formatted_address}}

test: {{googleMapsPlaceData.types.99}}
test: {{googleMapsPlaceData.types.99.asdasd}}
test: {{googleMapsPlaceData.opening_hours.open_non_existant_key}}
test: {{googleMapsPlaceData.opening_hours.open_non_existant_key.asdasd}}
```
A query to Katz's Delicatessen results in this note:
image

Undefined paths return the empty string.

<details>
<summary>Updating current notes without `place_id`</summary>
I'm using Templater to update my old geo tagged places that don't have this extra information. In my startup template I have:

```
templaterPlugin.registerEvent(tp.app.workspace.on('file-open', async (file) => {

    let needs_gmaps_place_id = false;
    let encodedCoords;
    await tp.app.fileManager.processFrontMatter(file, (frontmatter) => {
        needs_gmaps_place_id = ("location" in frontmatter) && !(("gmaps_place_id" in frontmatter));
        if (needs_gmaps_place_id) {
            encodedCoords = encodeURIComponent(frontmatter["location"]);
        }
    });

    if (needs_gmaps_place_id) {
        // Set gmap_place_id if we dont have it set:
        const googleMapsPlacesUrl = `https://maps.googleapis.com/maps/api/geocode/json?latlng=${encodedCoords}&key=[MY API KEY HERE]`
        const googleMapsJsonPlaceId = await tp.web.request(googleMapsPlacesUrl, "results.0.place_id");
        if (googleMapsJsonPlaceId && (googleMapsJsonPlaceId.length > 0)) {
            await tp.app.fileManager.processFrontMatter(file, (frontmatter) => {
                frontmatter["gmaps_place_id"] = googleMapsJsonPlaceId;
            });
        }
    }

    await tp.app.fileManager.processFrontMatter(file, (frontmatter) => {
        if ("location" in frontmatter) {
            const encodedCoords = encodeURIComponent(frontmatter["location"]);

            frontmatter["directions"] = "https://www.google.com/maps/dir/?api=1&destination=" + encodedCoords;
            frontmatter["location_link"] = "https://www.google.com/maps/search/?api=1&query=" + encodedCoords;
            if ("gmaps_place_id" in frontmatter) {
                // We can improve the search!
                const encodedPlaceId = encodeURIComponent(frontmatter["gmaps_place_id"]);
                // frontmatter["directions"] = `${frontmatter["directions"]}&destination_place_id=${encodedPlaceId}`;
                // if you use the coords, google maps doesnt show the name of the place when looking for directions
                frontmatter["directions"] = `https://www.google.com/maps/dir/?api=1&destination=null&destination_place_id=${encodedPlaceId}`;
                frontmatter["location_link"] = `${frontmatter["location_link"]}&query_place_id=${encodedPlaceId}`;
            }
        }
    });
}))
```

</details>

### CODE REVIEW

**Comment by esm7** [comment]
Thank you for this contribution, users will love it.
I added a few minor comments.
Except these, can you add documentation in the README?

**Comment by HalFrgrd** [comment]
Sure!

**Comment by HalFrgrd** [comment]
> Thank you for this contribution, users will love it. I added a few minor comments. Except these, can you add documentation in the README?

Let me know your comments, I cant see them atm

**Comment by esm7** [comment]
> > Thank you for this contribution, users will love it. I added a few minor comments. Except these, can you add documentation in the README?
> 
> Let me know your comments, I cant see them atm

So sorry, I forgot to submit the comments after writing them :facepalm:

**Comment by HalFrgrd** [comment]
I've added the google maps typing package so I can type annotate with `google.maps.places.PlaceResult`

**Comment by esm7** [comment]
Looks great, thank you!
I'm currently aiming to not make a 5.2.0 feature release, but a very big 6.0.0 release which I'm working on. So it means it will take at least a couple of weeks until users get this, hope you can do with a local build for now.

**Comment by WhyMe4** [comment]
I was about to ask if anyone had done this.
Question, will this template always create a new note, or could you use it to add to existing note? For example, if I had a note for restaurants, could add multiple businesses/locations on the one note?

**Pull request merged**
